"$schema" = "../gen/schemas/desktop-schema.json"

identifier = "taskbar-lyric"
local = true
windows = ["taskbar-lyric"]
platforms = ["windows"]

[[permissions]]
identifier = "core:event:allow-listen"
[[permissions]]
identifier = "core:event:allow-emit"
[[permissions]]
identifier = "core:event:allow-emit-to"
[[permissions]]
identifier = "core:event:allow-unlisten"
